version: '3.2'
services:
  hsrb_humble:
    #network_mode: host
    #ipc: host
    #pid: host
    network_mode: bridge #important for network setting
    build:
      context: .
      network: host
    container_name: hsrb_humble
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
    security_opt:
      - seccomp:unconfined

    privileged: true
    tty: true
    stdin_open: true

    command: ros2 launch hsrb_gazebo_launch hsrb_apartment_world.launch.py

